#!/bin/bash
set -e; set -u

function get_tree() {
	for file in *; do
		# Note - we're currently marking *all* files as 755 executable
		echo -ne "100755 $file\x00$(git hash-object -w "$file" | xxd -r -p)"
	done
}

commit=$({
	echo "tree $(get_tree | git hash-object -t tree -w --stdin)"
	test -e .git/refs/heads/master && echo "parent" $(cat .git/refs/heads/master)
	echo "author Example Author <author@example.com> 0 +0000"
	echo "committer Example Author <author@example.com> 0 +0000"
	echo
	cat # Read commit message from stdin
} | git hash-object -t commit -w --stdin)

echo $commit > .git/refs/heads/master
