#!/bin/bash
set -e; set -u

function get_tree() {
	for file in *; do
		# Note - we're currently marking *all* files as 755 executable
		echo -ne "100755 $file\x00$(git hash-object -w "$file" | xxd -r -p)"
	done
}

{
	echo "tree $(get_tree | git hash-object -t tree -w --stdin)"
	echo "author Example <test@example.com> 0 +0000"
	echo "committer Example <test@example.com> 0 +0000"
	echo
	cat # Read commit message from stdin
} | git hash-object -t commit -w --stdin > .git/refs/heads/master

